### PR TITLE
Added Shields to README

### PR DESCRIPTION
**Pull request by mahi-pas**
I added the license and architecture shields to the README file

Signed-off-by: Mahi Pasarkar <pasarkarmahi@gmail.com>

### CODE REVIEW

**Review by johnwalicki — APPROVED** [review]
LGTM Thanks!

**Comment by johnwalicki** [comment]
@mahi-pas If you can, amend this commit with your signature to acknowledge the DCO. If you have a local clone,
`git commit -s --amend -m "Add Shields to README"`
Then
`git push --force-with-lease origin example-branch`

If you created the commit in the github web page, I'm not sure of the steps.

**Comment by mahi-pas** [comment]
> 

I did this in github, I'm not sure how to edit it. In the future, I will make a local clone

**Comment by johnwalicki** [comment]
Merged - Thanks for contributing !

**Pull request merged**
